backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: public/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/articles'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Alt Text', name: 'alt', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured', name: 'featured', widget: 'boolean' }
      - { label: 'Body', name: 'body', widget: 'markdown' }